/* =========================================================
   Shared scenario banks for the Instructor Problem Generator
   — mirrors the curated scenario content in src/student/
   ========================================================= */

/* ── Z-Test & T-Test (single-sample) ── */
export const Z_T_SCENARIOS: Array<{ variable: string; unit: string; population: string }> = [
  { variable: 'test anxiety scores',               unit: 'points',              population: 'undergraduate students'       },
  { variable: 'working memory capacity',           unit: 'units',               population: 'college students'             },
  { variable: 'math anxiety ratings',              unit: 'points',              population: 'high school students'         },
  { variable: 'attention span',                    unit: 'minutes',             population: 'college-aged adults'          },
  { variable: 'cognitive flexibility scores',      unit: 'points',              population: 'young adults'                 },
  { variable: 'depression scores',                 unit: 'points',              population: 'clinical outpatients'         },
  { variable: 'self-efficacy ratings',             unit: 'points',              population: 'graduate students'            },
  { variable: 'social anxiety scores',             unit: 'points',              population: 'undergraduate students'       },
  { variable: 'procrastination scores',            unit: 'points',              population: 'college students'             },
  { variable: 'resilience scores',                 unit: 'points',              population: 'adults'                       },
  { variable: 'mindfulness ratings',               unit: 'points',              population: 'working adults'               },
  { variable: 'stress reactivity scores',          unit: 'points',              population: 'adults'                       },
  { variable: 'emotional regulation scores',       unit: 'points',              population: 'adolescents'                  },
  { variable: 'intrinsic motivation ratings',      unit: 'points',              population: 'middle school students'       },
  { variable: 'decision-making accuracy',          unit: '%',                   population: 'older adults'                 },
  { variable: 'creative problem-solving scores',   unit: 'points',              population: 'undergraduate students'       },
  { variable: 'verbal fluency scores',             unit: 'words/min',           population: 'adults'                       },
  { variable: 'spatial reasoning scores',          unit: 'points',              population: 'engineering students'         },
  { variable: 'executive function scores',         unit: 'points',              population: 'children aged 8–12'           },
  { variable: 'academic engagement ratings',       unit: 'points',              population: 'high school students'         },
  { variable: 'systolic blood pressure',           unit: 'mmHg',                population: 'adults aged 30–50'            },
  { variable: 'resting heart rate',                unit: 'bpm',                 population: 'sedentary adults'             },
  { variable: 'sleep duration',                    unit: 'hours',               population: 'shift workers'                },
  { variable: 'sleep quality index',               unit: 'points',              population: 'college students'             },
  { variable: 'fatigue severity scores',           unit: 'points',              population: 'adults with chronic illness'  },
  { variable: 'chronic pain intensity ratings',    unit: 'points',              population: 'adult patients'               },
  { variable: 'cortisol levels',                   unit: 'nmol/L',              population: 'adults under stress'          },
  { variable: 'grip strength',                     unit: 'kg',                  population: 'older adults'                 },
  { variable: 'reaction time',                     unit: 'ms',                  population: 'young adults'                 },
  { variable: 'body mass index',                   unit: 'kg/m²',               population: 'adults aged 25–45'            },
  { variable: 'physical activity level',           unit: 'MET-hours/week',      population: 'adults'                       },
  { variable: 'lung function',                     unit: '% predicted FEV1',    population: 'adults with asthma'           },
  { variable: 'resting metabolic rate',            unit: 'kcal/day',            population: 'healthy adults'               },
  { variable: 'blood glucose levels',              unit: 'mg/dL',               population: 'pre-diabetic adults'          },
  { variable: 'heart rate variability',            unit: 'ms',                  population: 'endurance athletes'           },
  { variable: 'reading comprehension scores',      unit: 'points',              population: 'fifth-grade students'         },
  { variable: 'exam performance scores',           unit: 'points',              population: 'undergraduate students'       },
  { variable: 'vocabulary test scores',            unit: 'points',              population: 'language learners'            },
  { variable: 'GPA',                               unit: 'points',              population: 'college freshmen'             },
  { variable: 'homework completion rates',         unit: '%',                   population: 'middle school students'       },
  { variable: 'classroom participation ratings',   unit: 'points',              population: 'eighth-grade students'        },
  { variable: 'critical thinking scores',          unit: 'points',              population: 'graduate students'            },
  { variable: 'academic self-efficacy scores',     unit: 'points',              population: 'high school seniors'          },
  { variable: 'note-taking quality ratings',       unit: 'points',              population: 'undergraduate students'       },
  { variable: 'peer collaboration scores',         unit: 'points',              population: 'elementary school students'   },
  { variable: 'job satisfaction scores',           unit: 'points',              population: 'full-time employees'          },
  { variable: 'workplace stress scores',           unit: 'points',              population: 'healthcare workers'           },
  { variable: 'burnout scores',                    unit: 'points',              population: 'medical residents'            },
  { variable: 'organizational commitment scores',  unit: 'points',              population: 'remote workers'               },
  { variable: 'daily step count',                  unit: 'steps',               population: 'office workers'               },
];

/* ── Independent-Samples T-Test ── */
export const IND_T_SCENARIOS: Array<{ variable: string; unit: string; group1: string; group2: string }> = [
  { variable: 'cortisol levels',                   unit: 'nmol/L',    group1: 'control group',                     group2: 'high-stress group'                  },
  { variable: 'academic motivation',               unit: 'points',    group1: 'lecture-based class',               group2: 'active-learning class'              },
  { variable: 'job satisfaction',                  unit: 'points',    group1: 'remote workers',                    group2: 'on-site workers'                    },
  { variable: 'pain tolerance threshold',          unit: 'units',     group1: 'sedentary adults',                  group2: 'regularly active adults'            },
  { variable: 'working memory score',              unit: 'points',    group1: 'non-meditators',                    group2: 'regular meditators'                 },
  { variable: 'sleep quality rating',              unit: 'points',    group1: 'shift workers',                     group2: 'day-shift workers'                  },
  { variable: 'test anxiety score',                unit: 'points',    group1: 'control group',                     group2: 'test-taking strategy training group' },
  { variable: 'emotional regulation score',        unit: 'points',    group1: 'waitlist control group',            group2: 'CBT group'                          },
  { variable: 'perceived stress score',            unit: 'points',    group1: 'first-year students',               group2: 'third-year students'                },
  { variable: 'heart rate variability',            unit: 'ms',        group1: 'recreational athletes',             group2: 'elite athletes'                     },
  { variable: 'reading comprehension score',       unit: 'points',    group1: 'standard instruction group',        group2: 'guided reading group'               },
  { variable: 'life satisfaction rating',          unit: 'points',    group1: 'adults without chronic pain',       group2: 'adults with chronic pain'           },
  { variable: 'reaction time',                     unit: 'ms',        group1: 'younger adults',                    group2: 'older adults'                       },
  { variable: 'vocabulary score',                  unit: 'points',    group1: 'monolingual adults',                group2: 'bilingual adults'                   },
  { variable: 'math performance',                  unit: 'points',    group1: 'fixed mindset group',               group2: 'growth mindset group'               },
  { variable: 'systolic blood pressure',           unit: 'mmHg',      group1: 'standard diet group',               group2: 'low-sodium diet group'              },
  { variable: 'creative thinking score',           unit: 'points',    group1: 'low nature exposure group',         group2: 'high nature exposure group'         },
  { variable: 'burnout score',                     unit: 'points',    group1: 'administrative staff',              group2: 'healthcare workers'                 },
  { variable: 'GPA',                               unit: 'points',    group1: 'students without mentors',          group2: 'students with mentors'              },
  { variable: 'cognitive flexibility score',       unit: 'points',    group1: 'monolingual children',              group2: 'bilingual children'                 },
  { variable: 'social anxiety score',              unit: 'points',    group1: 'in-person instruction group',       group2: 'online instruction group'           },
  { variable: 'sleep duration',                    unit: 'hours',     group1: 'sedentary adults',                  group2: 'regular exercisers'                 },
  { variable: 'decision-making accuracy',          unit: '%',         group1: 'sleep-deprived adults',             group2: 'rested adults'                      },
  { variable: 'intrinsic motivation score',        unit: 'points',    group1: 'control environment group',         group2: 'autonomy-supportive environment group'},
  { variable: 'attention span',                    unit: 'minutes',   group1: 'waitlist control group',            group2: 'mindfulness training group'         },
  { variable: 'resilience score',                  unit: 'points',    group1: 'limited social support group',      group2: 'strong social support group'        },
  { variable: 'exam performance',                  unit: 'points',    group1: 'massed practice group',             group2: 'spaced practice group'              },
  { variable: 'fatigue score',                     unit: 'points',    group1: 'control group',                     group2: 'yoga intervention group'            },
  { variable: 'self-efficacy score',               unit: 'points',    group1: 'independent study group',           group2: 'peer tutoring group'                },
  { variable: 'daily step count',                  unit: 'steps',     group1: 'seated desk users',                 group2: 'standing desk users'                },
  { variable: 'resting heart rate',                unit: 'bpm',       group1: 'non-swimmers',                      group2: 'regular swimmers'                   },
  { variable: 'depression score',                  unit: 'points',    group1: 'stretching control group',          group2: 'aerobic exercise group'             },
  { variable: 'organizational commitment score',   unit: 'points',    group1: 'fixed schedule workers',            group2: 'flexible schedule workers'          },
  { variable: 'pain intensity rating',             unit: 'points',    group1: 'placebo group',                     group2: 'pain management program group'      },
  { variable: 'productivity rating',               unit: 'points',    group1: 'five-day workweek group',           group2: 'four-day workweek group'            },
  { variable: 'math anxiety score',                unit: 'points',    group1: 'control group',                     group2: 'math anxiety intervention group'    },
  { variable: 'peer collaboration score',          unit: 'points',    group1: 'competitive learning group',        group2: 'cooperative learning group'         },
  { variable: 'spatial reasoning score',           unit: 'points',    group1: 'non-players',                       group2: 'video game players'                 },
  { variable: 'blood glucose level',               unit: 'mg/dL',     group1: 'low-fiber diet group',              group2: 'high-fiber diet group'              },
  { variable: 'empathy score',                     unit: 'points',    group1: 'standard curriculum group',         group2: 'arts education group'               },
  { variable: 'grip strength',                     unit: 'kg',        group1: 'aerobic training group',            group2: 'resistance training group'          },
  { variable: 'executive function score',          unit: 'points',    group1: 'monolingual students',              group2: 'bilingual students'                 },
  { variable: 'loneliness score',                  unit: 'points',    group1: 'urban residents',                   group2: 'rural residents'                    },
  { variable: 'academic engagement score',         unit: 'points',    group1: 'lecture-only group',                group2: 'project-based learning group'       },
  { variable: 'mood rating',                       unit: 'points',    group1: 'no exercise group',                 group2: 'morning exercise group'             },
  { variable: 'critical thinking score',           unit: 'points',    group1: 'standard instruction group',        group2: 'Socratic questioning group'         },
  { variable: 'emotional exhaustion score',        unit: 'points',    group1: 'workers with adequate breaks',      group2: 'workers without adequate breaks'    },
  { variable: 'concentration score',               unit: 'points',    group1: 'noisy environment group',           group2: 'quiet environment group'            },
  { variable: 'health behavior score',             unit: 'points',    group1: 'individual intervention group',     group2: 'peer support group'                 },
  { variable: 'life purpose score',                unit: 'points',    group1: 'older adults without social roles', group2: 'older adults with social roles'     },
];

/* ── Repeated-Measures T-Test ── */
export const REP_T_SCENARIOS: Array<{ variable: string; unit: string; pre: string; post: string }> = [
  { variable: 'anxiety score',                     unit: 'points',         pre: 'Pre-Intervention',             post: 'Post-Intervention'            },
  { variable: 'systolic blood pressure',           unit: 'mmHg',           pre: 'Baseline',                     post: '8-Week Follow-Up'             },
  { variable: 'cognitive performance score',       unit: 'points',         pre: 'Before Training',              post: 'After Training'               },
  { variable: 'cortisol level',                    unit: 'nmol/L',         pre: 'Pre-Test',                     post: 'Post-Test'                    },
  { variable: 'reaction time',                     unit: 'ms',             pre: 'Pre-Practice',                 post: 'Post-Practice'                },
  { variable: 'pain intensity rating',             unit: 'points',         pre: 'Week 1',                       post: 'Week 8'                       },
  { variable: 'depression score',                  unit: 'points',         pre: 'Pre-Treatment',                post: 'Post-Treatment'               },
  { variable: 'resting heart rate',                unit: 'bpm',            pre: 'Baseline',                     post: '12-Week Follow-Up'            },
  { variable: 'working memory score',              unit: 'points',         pre: 'Pre-Training',                 post: 'Post-Training'                },
  { variable: 'sleep quality rating',              unit: 'points',         pre: 'Pre-Intervention',             post: '6-Week Follow-Up'             },
  { variable: 'self-efficacy score',               unit: 'points',         pre: 'Start of Semester',            post: 'End of Semester'              },
  { variable: 'stress rating',                     unit: 'points',         pre: 'Before Mindfulness Session',   post: 'After Mindfulness Session'    },
  { variable: 'fatigue score',                     unit: 'points',         pre: 'Pre-Exercise Program',         post: 'Post-Exercise Program'        },
  { variable: 'math performance',                  unit: 'points',         pre: 'Pre-Test',                     post: 'Post-Test'                    },
  { variable: 'physical endurance',                unit: 'MET-hours/week', pre: 'Baseline',                     post: '10-Week Training'             },
  { variable: 'mood rating',                       unit: 'points',         pre: 'Morning',                      post: 'Evening'                      },
  { variable: 'executive function score',          unit: 'points',         pre: 'Before Sleep Restriction',     post: 'After Sleep Restriction'      },
  { variable: 'blood glucose level',               unit: 'mg/dL',          pre: 'Fasting',                      post: '2-Hour Post-Meal'             },
  { variable: 'academic motivation score',         unit: 'points',         pre: 'Pre-Counseling',               post: 'Post-Counseling'              },
  { variable: 'reading comprehension score',       unit: 'points',         pre: 'Pre-Test',                     post: 'Post-Test'                    },
  { variable: 'pain tolerance threshold',          unit: 'units',          pre: 'Pre-Acupuncture',              post: 'Post-Acupuncture'             },
  { variable: 'loneliness score',                  unit: 'points',         pre: 'Before Group Therapy',         post: 'After Group Therapy'          },
  { variable: 'focus rating',                      unit: 'points',         pre: 'Without Background Music',     post: 'With Background Music'        },
  { variable: 'grip strength',                     unit: 'kg',             pre: 'Pre-Resistance Training',      post: 'Post-Resistance Training'     },
  { variable: 'life satisfaction score',           unit: 'points',         pre: 'Pre-Gratitude Intervention',   post: 'Post-Gratitude Intervention'  },
  { variable: 'concentration score',               unit: 'points',         pre: 'Before Break',                 post: 'After Break'                  },
  { variable: 'heart rate variability',            unit: 'ms',             pre: 'Baseline',                     post: '8-Week Follow-Up'             },
  { variable: 'burnout score',                     unit: 'points',         pre: 'Pre-Wellness Program',         post: 'Post-Wellness Program'        },
  { variable: 'exam performance',                  unit: 'points',         pre: 'Midterm',                      post: 'Final Exam'                   },
  { variable: 'social support rating',             unit: 'points',         pre: 'Before Peer Program',          post: 'After Peer Program'           },
  { variable: 'resilience score',                  unit: 'points',         pre: 'Pre-Coaching',                 post: 'Post-Coaching'                },
  { variable: 'vocabulary score',                  unit: 'points',         pre: 'Pre-Immersion',                post: 'Post-Immersion'               },
  { variable: 'organizational commitment score',   unit: 'points',         pre: 'Before Management Change',     post: 'After Management Change'      },
  { variable: 'test anxiety score',                unit: 'points',         pre: 'Before Exam Prep Workshop',    post: 'After Exam Prep Workshop'     },
  { variable: 'empathy score',                     unit: 'points',         pre: 'Before Role-Playing Exercise', post: 'After Role-Playing Exercise'  },
  { variable: 'emotional regulation score',        unit: 'points',         pre: 'Before DBT Program',           post: 'After DBT Program'            },
  { variable: 'spatial reasoning score',           unit: 'points',         pre: 'Pre-Training',                 post: 'Post-Training'                },
  { variable: 'academic engagement score',         unit: 'points',         pre: 'First Week',                   post: 'Final Week'                   },
  { variable: 'self-compassion score',             unit: 'points',         pre: 'Pre-Workshop',                 post: 'Post-Workshop'                },
  { variable: 'perceived workload score',          unit: 'points',         pre: 'Before Workflow Redesign',     post: 'After Workflow Redesign'      },
  { variable: 'resting metabolic rate',            unit: 'kcal/day',       pre: 'Pre-Diet Intervention',        post: 'Post-Diet Intervention'       },
  { variable: 'intrinsic motivation score',        unit: 'points',         pre: 'Fall Semester',                post: 'Spring Semester'              },
  { variable: 'balance score',                     unit: 'points',         pre: 'Pre-Physical Therapy',         post: 'Post-Physical Therapy'        },
  { variable: 'daily step count',                  unit: 'steps',          pre: 'Before Fitness App',           post: 'After 30-Day App Use'         },
  { variable: 'critical thinking score',           unit: 'points',         pre: 'Freshman Year',                post: 'Senior Year'                  },
  { variable: 'procrastination score',             unit: 'points',         pre: 'Before Time-Management Training', post: 'After Time-Management Training'},
  { variable: 'emotional exhaustion score',        unit: 'points',         pre: 'Pre-Vacation',                 post: 'Post-Vacation'                },
  { variable: 'reading fluency score',             unit: 'words/min',      pre: 'September',                    post: 'May'                          },
  { variable: 'leadership effectiveness score',    unit: 'points',         pre: 'Before Leadership Program',    post: 'After Leadership Program'     },
  { variable: 'mindfulness score',                 unit: 'points',         pre: 'Pre-MBSR',                     post: 'Post-MBSR'                    },
];

/* ── Pearson Correlation & Linear Regression ── */
export const PEARSON_REG_SCENARIOS: Array<{
  variable_x: string; unit_x: string;
  variable_y: string; unit_y: string;
  population: string;
}> = [
  { variable_x: 'weekly exercise duration',        unit_x: 'minutes',        variable_y: 'resting heart rate',          unit_y: 'bpm',          population: 'sedentary adults'          },
  { variable_x: 'sleep duration',                  unit_x: 'hours',          variable_y: 'reaction time',               unit_y: 'ms',           population: 'young adults'              },
  { variable_x: 'anxiety score',                   unit_x: 'points',         variable_y: 'cortisol level',              unit_y: 'nmol/L',       population: 'adults under stress'       },
  { variable_x: 'weekly study hours',              unit_x: 'hours',          variable_y: 'exam score',                  unit_y: 'points',       population: 'undergraduate students'    },
  { variable_x: 'social support rating',           unit_x: 'points',         variable_y: 'depression score',            unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'daily step count',                unit_x: 'steps',          variable_y: 'body mass index',             unit_y: 'kg/m²',        population: 'office workers'            },
  { variable_x: 'screen time',                     unit_x: 'hours/day',      variable_y: 'sleep quality score',         unit_y: 'points',       population: 'college students'          },
  { variable_x: 'caffeine intake',                 unit_x: 'mg/day',         variable_y: 'resting heart rate',          unit_y: 'bpm',          population: 'adults'                    },
  { variable_x: 'mindfulness practice',            unit_x: 'min/week',       variable_y: 'anxiety score',               unit_y: 'points',       population: 'working adults'            },
  { variable_x: 'GPA',                             unit_x: 'points',         variable_y: 'academic self-efficacy',      unit_y: 'points',       population: 'college freshmen'          },
  { variable_x: 'stress score',                    unit_x: 'points',         variable_y: 'sleep duration',              unit_y: 'hours',        population: 'graduate students'         },
  { variable_x: 'pain intensity',                  unit_x: 'points',         variable_y: 'fatigue score',               unit_y: 'points',       population: 'adult patients'            },
  { variable_x: 'daily reading time',              unit_x: 'min/day',        variable_y: 'vocabulary score',            unit_y: 'points',       population: 'high school students'      },
  { variable_x: 'physical activity level',         unit_x: 'MET-hours/week', variable_y: 'systolic blood pressure',     unit_y: 'mmHg',         population: 'adults aged 40–60'         },
  { variable_x: 'social media use',                unit_x: 'hours/day',      variable_y: 'loneliness score',            unit_y: 'points',       population: 'undergraduate students'    },
  { variable_x: 'self-efficacy score',             unit_x: 'points',         variable_y: 'academic performance',        unit_y: 'points',       population: 'middle school students'    },
  { variable_x: 'emotional regulation score',      unit_x: 'points',         variable_y: 'relationship satisfaction',   unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'job satisfaction score',          unit_x: 'points',         variable_y: 'burnout score',               unit_y: 'points',       population: 'healthcare workers'        },
  { variable_x: 'hours of sleep',                  unit_x: 'hours',          variable_y: 'executive function score',    unit_y: 'points',       population: 'college students'          },
  { variable_x: 'grip strength',                   unit_x: 'kg',             variable_y: 'physical function score',     unit_y: 'points',       population: 'older adults'              },
  { variable_x: 'cortisol level',                  unit_x: 'nmol/L',         variable_y: 'working memory score',        unit_y: 'points',       population: 'adults under stress'       },
  { variable_x: 'meditation frequency',            unit_x: 'sessions/week',  variable_y: 'stress score',                unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'age',                             unit_x: 'years',          variable_y: 'reaction time',               unit_y: 'ms',           population: 'adults aged 20–70'         },
  { variable_x: 'exercise frequency',              unit_x: 'sessions/week',  variable_y: 'depression score',            unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'parent involvement score',        unit_x: 'points',         variable_y: 'child academic score',        unit_y: 'points',       population: 'elementary students'       },
  { variable_x: 'noise exposure',                  unit_x: 'dB',             variable_y: 'concentration score',         unit_y: 'points',       population: 'office workers'            },
  { variable_x: 'homework time',                   unit_x: 'min/day',        variable_y: 'GPA',                         unit_y: 'points',       population: 'high school students'      },
  { variable_x: 'optimism score',                  unit_x: 'points',         variable_y: 'resilience score',            unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'hours of sunlight exposure',      unit_x: 'hours/day',      variable_y: 'mood rating',                 unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'sleep efficiency',                unit_x: '%',              variable_y: 'daytime fatigue score',       unit_y: 'points',       population: 'shift workers'             },
  { variable_x: 'intrinsic motivation',            unit_x: 'points',         variable_y: 'creative output score',       unit_y: 'points',       population: 'graduate students'         },
  { variable_x: 'peer support score',              unit_x: 'points',         variable_y: 'academic engagement',         unit_y: 'points',       population: 'middle school students'    },
  { variable_x: 'heart rate variability',          unit_x: 'ms',             variable_y: 'stress reactivity score',     unit_y: 'points',       population: 'endurance athletes'        },
  { variable_x: 'social interaction frequency',    unit_x: 'count/week',     variable_y: 'loneliness score',            unit_y: 'points',       population: 'older adults'              },
  { variable_x: 'pain score',                      unit_x: 'points',         variable_y: 'sleep quality score',         unit_y: 'points',       population: 'adult patients'            },
  { variable_x: 'dietary fiber intake',            unit_x: 'g/day',          variable_y: 'blood glucose level',         unit_y: 'mg/dL',        population: 'pre-diabetic adults'       },
  { variable_x: 'self-compassion score',           unit_x: 'points',         variable_y: 'anxiety score',               unit_y: 'points',       population: 'undergraduate students'    },
  { variable_x: 'perceived workload score',        unit_x: 'points',         variable_y: 'job performance rating',      unit_y: 'points',       population: 'full-time employees'       },
  { variable_x: 'vocabulary size',                 unit_x: 'words known',    variable_y: 'reading comprehension',       unit_y: 'points',       population: 'language learners'         },
  { variable_x: 'attention span',                  unit_x: 'minutes',        variable_y: 'exam performance',            unit_y: 'points',       population: 'undergraduate students'    },
  { variable_x: 'parental warmth score',           unit_x: 'points',         variable_y: 'child self-esteem',           unit_y: 'points',       population: 'elementary students'       },
  { variable_x: 'weekly study sessions',           unit_x: 'count/week',     variable_y: 'exam performance',            unit_y: 'points',       population: 'undergraduate students'    },
  { variable_x: 'physical activity',               unit_x: 'steps/day',      variable_y: 'sleep quality score',         unit_y: 'points',       population: 'adults aged 30–50'         },
  { variable_x: 'tech skill score',                unit_x: 'points',         variable_y: 'remote work productivity',    unit_y: 'points',       population: 'remote workers'            },
  { variable_x: 'childhood SES score',             unit_x: 'points',         variable_y: 'cognitive flexibility score', unit_y: 'points',       population: 'young adults'              },
  { variable_x: 'resting heart rate',              unit_x: 'bpm',            variable_y: 'aerobic fitness score',       unit_y: 'points',       population: 'adults'                    },
  { variable_x: 'daily fruit and vegetable intake',unit_x: 'servings/day',   variable_y: 'energy level score',          unit_y: 'points',       population: 'college students'          },
  { variable_x: 'cognitive load score',            unit_x: 'points',         variable_y: 'decision accuracy',           unit_y: '%',            population: 'healthcare workers'        },
  { variable_x: 'emotional intelligence score',    unit_x: 'points',         variable_y: 'leadership effectiveness',    unit_y: 'points',       population: 'managers'                  },
  { variable_x: 'number of hours worked per week', unit_x: 'hours',          variable_y: 'work-life balance score',     unit_y: 'points',       population: 'full-time employees'       },
];

/* ── Helper: pick a random element ── */
export function rScenario<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}
